#:schema node_modules/wrangler/config-schema.json
name = "ai-trader-api"
main = "src/index.ts"
compatibility_date = "2025-01-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[vars]

[durable_objects]

[triggers]
crons = ["*/15 * * * *"]

[[migrations]]

[[kv_namespaces]]
binding = "KV"
id = "19f61b774756438ca781e93e120b2862"
